const portfolioObjects = [
	{
		title: "QuizIt!",
		urlDemo: "https://fierce-oasis-31783.herokuapp.com/",
		urlCode: "https://github.com/Binary-Squad/QuizIt",
		details: [
			"Bootstrap",
			"MERN",
			"Socket.io",
			"Passportjs",
			"CORS",
			"JWT",
			"Mongoose",
			"Heroku",
			"Animation",
		],
	},
	{
		title: "JP&apos;s Portfolio",
		urlDemo: "https://peaceful-inlet-20360.herokuapp.com/",
		urlCode: "https://github.com/jonmpan/new-portfolio",
		details: [
			"Materialize",
			"React",
			"Nodejs",
			"Express",
			"Heroku",
			"SSL",
			"Components",
			"Mobile",
			"Desktop",
		],
	},
	{
		title: "Closets x3",
		urlDemo: "https://floating-thicket-42503.herokuapp.com/",
		urlCode: "https://github.com/the-bristools/closetsclosetsclosets",
		details: [
			"Materialize",
			"Handlebars",
			"Nodejs",
			"MVC",
			"Express",
			"JQuery",
			"ORM",
			"Sequelize",
			"Heroku",
		],
	},
	// {
	// 	title: "cAPI-PASTE",
	// 	urlDemo: "https://first-project-tom-jon-suneetha.github.io/cAPI-PASTE/",
	// 	urlCode: "https://github.com/First-Project-Tom-Jon-Suneetha/cAPI-PASTE",
	// 	details: [
	// 		"Bootstrap",
	// 		"AceText",
	// 		"Jquery",
	// 		"AJAX",
	// 		"GoogleAPI",
	// 		"JQuery",
	// 		"Giphy",
	// 		"YoutubeAPI",
	// 		"Github Pages",
	// 		"Animation",
	// 	],
	// },
	// {
	// 	title: "OmnomBurger",
	// 	urlDemo: "https://fast-retreat-55192.herokuapp.com/",
	// 	urlCode: "https://github.com/jonmpan/Omnom-Dat-Burger-Sequelize",
	// 	details: [
	// 		"Materialize",
	// 		"Sequelize",
	// 		"Nodejs",
	// 		"JQuery",
	// 		"ORM",
	// 		"REST",
	// 		"Express",
	// 		"MVC",
	// 		"Animation",
	// 	],
	// },
	// {
	// 	title: "Giphy Ajax",
	// 	urlDemo: "https://jonmpan.github.io/ajax-assignment/",
	// 	urlCode: "https://github.com/jonmpan/ajax-assignment/",
	// 	details: [
	// 		"JQuery",
	// 		"Ajax",
	// 		"GiphyAPI",
	// 		"CORS",
	// 		"JQuery",
	// 		"JWT",
	// 		"Animation",
	// 		"Video",
	// 		"Audio",
	// 	],
	// },
	// {
	// 	title: "Cirno Clicker",
	// 	urlDemo: "https://jonmpan.github.io/firebase-assignment/player1",
	// 	urlCode: "https://github.com/jonmpan/firebase-assignment",
	// 	details: [
	// 		"Cirno",
	// 		"Game",
	// 		"Firebase",
	// 		"JQuery",
	// 		"Javascript",
	// 		"Audio",
	// 		"Animation",
	// 	],
	// },
	// {
	// 	title: "Cirno Math",
	// 	urlDemo: "https://jonmpan.github.io/trivia-game/",
	// 	urlCode: "https://github.com/jonmpan/trivia-game",
	// 	details: ["Cirno", "Game", "Math", "Jquery", "Video", "Audio"],
	// },
	// {
	// 	title: "Cirno Hangman",
	// 	urlDemo: "https://jonmpan.github.io/hangman-game/",
	// 	urlCode: "https://github.com/jonmpan/hangman-game",
	// 	details: ["Cirno", "Game", "JQuery", "Animation", "Audio"],
	// },
];

module.exports = portfolioObjects;
